# Generated by Django 4.2.2 on 2023-12-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='performance_coefficient',
            field=models.FloatField(default=1.0),
        ),
    ]
