# Generated by Django 4.2.2 on 2024-02-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_performance_coefficient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='performance_coefficient',
            field=models.FloatField(default=0.0),
        ),
    ]
