# Generated by Django 4.2.2 on 2023-08-26 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtask',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, validators=[users.validators.validate_team_member]),
        ),
        migrations.AddField(
            model_name='teamboard',
            name='admins',
            field=models.ManyToManyField(related_name='teamboard_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamboard',
            name='participants',
            field=models.ManyToManyField(related_name='teamboard_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.board'),
        ),
        migrations.AddField(
            model_name='board',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
