# Generated by Django 4.2.2 on 2023-08-22 09:06

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('F', 'Future'), ('PR', 'In progress'), ('D', 'Done'), ('O', 'Overdue')], default='F', max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2023, 8, 22, 9, 6, 11, 492856, tzinfo=datetime.timezone.utc))]))]),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2023, 8, 22, 9, 6, 11, 492856, tzinfo=datetime.timezone.utc))]),
        ),
    ]
