# Generated by Django 4.2.2 on 2023-08-26 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_alter_teamtask_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamtask',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, validators=[users.validators.validate_team_member]),
        ),
    ]
