# Generated by Django 4.2.2 on 2023-08-22 09:27

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_end_date_alter_task_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=django.utils.timezone.now)]))]),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=django.utils.timezone.now)]),
        ),
    ]
