# Generated by Django 4.2.2 on 2023-08-23 10:23

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=django.utils.timezone.now, message='Ensure this value is greater than or equal to your current time ')]),
        ),
    ]
